-- Tiny bilingual (Persian + English) catalog for tests.
-- GENERATED by fixtures/generate_products_sample.php — do not edit by hand.
-- normalized_title / normalized_desc are produced by the canonical Normalizer
-- (contract 1). Loading this file requires db/schema.sql to be applied first.

SET NAMES utf8mb4;

INSERT INTO products
    (product_id, title, description, normalized_title, normalized_desc,
     brand, category, model, price, stock, url, image, popularity)
VALUES
    (1001, 'Apple iPhone 15 Pro Max 256GB', 'Apple iPhone 15 Pro Max smartphone with 256GB storage and titanium body', 'apple iphone 15 pro max 256gb', 'apple iphone 15 pro max smartphone with 256gb storage and titanium body', 'Apple', 'Mobile Phone', 'IP15PROMAX', 1299.0000, 12, '/product/iphone-15-pro-max', '/image/iphone15.jpg', 1000),
    (1002, 'گوشی موبایل اپل آیفون ۱۵ پرو مکس', 'گوشی موبایل اپل آیفون ۱۵ پرو مکس با حافظه ۲۵۶ گیگابایت و بدنه تیتانیوم', 'گوشی موبایل اپل ایفون 15 پرو مکس', 'گوشی موبایل اپل ایفون 15 پرو مکس با حافظه 256 گیگابایت و بدنه تیتانیوم', 'Apple', 'گوشی موبایل', 'IP15PROMAX', 1299.0000, 12, '/product/iphone-15-pro-max-fa', '/image/iphone15.jpg', 980),
    (1003, 'Samsung Galaxy S24 Ultra', 'Samsung Galaxy S24 Ultra smartphone with S Pen and 200MP camera', 'samsung galaxy s24 ultra', 'samsung galaxy s24 ultra smartphone with s pen and 200mp camera', 'Samsung', 'Mobile Phone', 'SM-S928', 1199.0000, 20, '/product/galaxy-s24-ultra', '/image/s24.jpg', 850),
    (1004, 'گوشی سامسونگ گلکسی اس ۲۴ اولترا', 'گوشی سامسونگ گلکسی اس ۲۴ اولترا با قلم اس پن و دوربین ۲۰۰ مگاپیکسل', 'گوشی سامسونگ گلکسی اس 24 اولترا', 'گوشی سامسونگ گلکسی اس 24 اولترا با قلم اس پن و دوربین 200 مگاپیکسل', 'Samsung', 'گوشی موبایل', 'SM-S928', 1199.0000, 20, '/product/galaxy-s24-ultra-fa', '/image/s24.jpg', 830),
    (1005, 'ASUS VivoBook Laptop 15', 'ASUS VivoBook 15 laptop with Intel Core i7 processor and 16GB RAM', 'asus vivobook laptop 15', 'asus vivobook 15 laptop with intel core i7 processor and 16gb ram', 'ASUS', 'Laptop', 'X1504', 799.0000, 7, '/product/asus-vivobook-15', '/image/vivobook.jpg', 500),
    (1006, 'لپ تاپ ایسوس ویووبوک ۱۵', 'لپ تاپ ایسوس ویووبوک با پردازنده اینتل کور آی هفت و رم ۱۶ گیگابایت', 'لپ تاپ ایسوس ویووبوک 15', 'لپ تاپ ایسوس ویووبوک با پردازنده اینتل کور ای هفت و رم 16 گیگابایت', 'ASUS', 'لپ تاپ', 'X1504', 799.0000, 7, '/product/asus-vivobook-15-fa', '/image/vivobook.jpg', 480),
    (1007, 'Apple MacBook Air M2 13 inch', 'Apple MacBook Air laptop with M2 chip and 13 inch Retina display', 'apple macbook air m2 13 inch', 'apple macbook air laptop with m2 chip and 13 inch retina display', 'Apple', 'Laptop', 'MLY33', 1099.0000, 5, '/product/macbook-air-m2', '/image/macbook.jpg', 700),
    (1008, 'لپ تاپ اپل مک بوک ایر ام ۲', 'لپ تاپ اپل مک بوک ایر با تراشه ام ۲ و نمایشگر ۱۳ اینچ رتینا', 'لپ تاپ اپل مک بوک ایر ام 2', 'لپ تاپ اپل مک بوک ایر با تراشه ام 2 و نمایشگر 13 اینچ رتینا', 'Apple', 'لپ تاپ', 'MLY33', 1099.0000, 5, '/product/macbook-air-m2-fa', '/image/macbook.jpg', 680),
    (1009, 'Sony WH-1000XM5 Wireless Headphones', 'Sony WH-1000XM5 noise cancelling wireless over-ear headphones', 'sony wh1000xm5 wireless headphones', 'sony wh1000xm5 noise cancelling wireless overear headphones', 'Sony', 'Headphone', 'WH1000XM5', 349.0000, 30, '/product/sony-wh-1000xm5', '/image/sony-headphones.jpg', 600),
    (1010, 'هدفون بی‌سیم سونی مدل WH-1000XM5', 'هدفون بی‌سیم سونی با قابلیت حذف نویز و صدای فراگیر روی گوش', 'هدفون بیسیم سونی مدل wh1000xm5', 'هدفون بیسیم سونی با قابلیت حذف نویز و صدای فراگیر روی گوش', 'Sony', 'هدفون', 'WH1000XM5', 349.0000, 30, '/product/sony-wh-1000xm5-fa', '/image/sony-headphones.jpg', 560),
    (1011, 'Sony Alpha A7 IV Mirrorless Camera', 'Sony Alpha A7 IV full-frame mirrorless camera with 33MP sensor', 'sony alpha a7 iv mirrorless camera', 'sony alpha a7 iv fullframe mirrorless camera with 33mp sensor', 'Sony', 'Camera', 'ILCE-7M4', 2499.0000, 4, '/product/sony-a7-iv', '/image/sony-a7.jpg', 300),
    (1012, 'دوربین بدون آینه سونی آلفا A7 مارک ۴', 'دوربین بدون آینه سونی آلفا فول‌فریم با سنسور ۳۳ مگاپیکسل', 'دوربین بدون اینه سونی الفا a7 مارک 4', 'دوربین بدون اینه سونی الفا فولفریم با سنسور 33 مگاپیکسل', 'Sony', 'دوربین', 'ILCE-7M4', 2499.0000, 4, '/product/sony-a7-iv-fa', '/image/sony-a7.jpg', 280),
    (1013, 'LG OLED TV 55 inch C3', 'LG OLED evo C3 55 inch 4K smart TV with webOS', 'lg oled tv 55 inch c3', 'lg oled evo c3 55 inch 4k smart tv with webos', 'LG', 'Television', 'OLED55C3', 1499.0000, 9, '/product/lg-oled-c3-55', '/image/lg-oled.jpg', 400),
    (1014, 'تلویزیون ال‌جی اولد ۵۵ اینچ مدل C3', 'تلویزیون هوشمند ال‌جی اولد ۴K پنجاه و پنج اینچ با سیستم عامل وب او اس', 'تلویزیون الجی اولد 55 اینچ مدل c3', 'تلویزیون هوشمند الجی اولد 4k پنجاه و پنج اینچ با سیستم عامل وب او اس', 'LG', 'تلویزیون', 'OLED55C3', 1499.0000, 9, '/product/lg-oled-c3-55-fa', '/image/lg-oled.jpg', 380);
